### ISSUE TITLE
CGP1: Static Page

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#1]
Create Static pages module.
This module is a tiny CMS module, which allow the admin to create static page.
To create page you need to have the following fields:
1- Title
2- Body ( WYSIWYG editor )
3- Menu:
3-1- title
3-2- path
3-3- parent item
4- save button
5- deactivate button

**Comment by lebaz20** [comment]
@ahmedelbougha @babanesma  I guess static page CRUD is ready now for testing

**Comment by babanesma** [comment]
- warning `( ! ) Warning: gzuncompress(): data error` is appeared when attempting to edit the page , and the page body is not appeared ( not every time )
