### ISSUE TITLE
CGP100: Instructor Directory

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#100]
Create a list of instructors accessible to all users
Create details page per instructor

**Comment by lebaz20** [comment]
- [x] Create instructor action using paginator
- [x] Create more action
- [x] Grant normal user access to both routes
- [x] Create views for both actions with translated content
- [x] Update paginator to support calls with joins

**Comment by lebaz20** [comment]
Organization create fails throwing error:
`Fatal error: Call to undefined method Translation\Service\Translator\TranslatorHandler::getCurrentLocale() in /var/www/html/module/Organizations/src/Organizations/Form/OrgForm.php on line 734`

**Comment by babanesma** [comment]
new bug created with the last comment
