### ISSUE TITLE
CGP101: Enrol in CIP and payment

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#101]
- Instructor should be the only one able to enroll in training for the trainer
- Enrollment workflow available for instructor

**Comment by lebaz20** [comment]
- [x] Update view for instructor calendar
- [x] Update instructor action to support enroll when token is sent back

**Comment by babanesma** [comment]
- merge development branch into this branch to retrieve the new theme 
- update the error message when there is no CIP course
