### ISSUE TITLE
CGP104: Hijri Calendar

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#104]
- Display hijri calendar via all calendars
- Modify date fields in all entities
- Handle date changes every month

**Comment by ahmedReda1** [comment]
##Forms with new Hijri calendar
- [x] user
- [x] Course Event
- [x] Organization
- [x] Exam Booking
- [x] renewal

**Comment by babanesma** [comment]
- [x] This error appears sometimes 

```
Uncaught TypeError: Cannot read property 'formatDate' of undefined
```
- [x] Make the normal calendar loads in arabic when the locale is arabic as what happens with hijri calendar 
- [x] fix design in arabic

**Comment by babanesma** [comment]
The plugin is working good , but it is retrieving a day behind in hirjrian calendar . 
Try to use Umm al-Qura Calendar from the same plugin , as it is more accurate .

**Comment by ahmedReda1** [comment]
- [x] using "Umm el Qura" calendar instead of "Islamic" calendar
- [x] removing javascript logs
