### ISSUE TITLE
CGP105: Public and Private training workflow

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#105]
Public workflow
- User has a calendar-like page where each course event has number of seats field and reserve button and course is updated 
- If course has no enough places a message is displayed stopping action/ action should handle if called with not enough places
- A mail is sent to admin with user details ,course event details and number of seats
- Admin has a list of quote requests mentioning user name ,course name ,status and public type with process page
- Admin process form has course event details read only beside unit price field with course price displayed as reference greyed out, and discount field -not percentage- with total = unit price \* seats number - discount and wire transfer if available
- A mail is sent to client to issue purchase with accept or decline 
- A command would check quotes with ‘pending payment’ or ‘pending re-payment’ status since a number of days, if more than x, then quote is deleted and course places are released
- Client has page with quotes and their status with process page
- Client process has decline and accept buttons with cost described
- Decline would delete quote and release course reserved places
- Accept would submit form with wire transfer uploaded [required field]
- A mail is sent to admin to revise wire transfer
- Admin process wire transfer with accept or decline
- A mail is sent back to client with status and invoice if accepted
- Client process page now display invoice details
- Cancelled requests appear for admin with no process but not appear for client

Private workflow
- User has a calendar-like page where each course has preferred date and venue [‘Customer premises’, ‘Company premises’, ‘Hotel / Other venue’] with reserve button and course is updated 
- A mail is sent to admin with user details and course details and submitted data
- Admin has a list of quote requests mentioning user name ,course name, status and private type with process page
- Admin process has price field with course price displayed as reference greyed out, and discount field -not percentage- with total = price - discount and wire transfer if available
- A mail is sent to client to issue purchase with accept or decline
- Client has page with quotes and their status with process page
- Client process has decline and accept buttons with cost described
- Decline would delete quote and course event
- Accept would submit form with wire transfer uploaded [required field]
- A mail is sent to admin to revise wire transfer
- Admin process wire transfer with accept
- A mail is sent back to client with invoice
- Client process page now display invoice details
- Cancelled requests appear for admin with no process but not appear for client

**Comment by lebaz20** [comment]
Entity
- [x] PublicQuote -> user | course event | seats | unit price | discount | wire transfer | status
- [x] PrivateQuote -> user | course | course event | preferred date | venue | price | discount | wire transfer | status

Quote status 
- [x] pending pricing| pending payment | pending review | pending re-payment | ready

Command
- [x] Get public quotes with status ‘inactive’ and date modified less than today - x = 10 days
- [x] Update quote course event with students number subtracted quote reserved seats
- [x] Remove quote
- [x] Flush at the end

ACL
- [x] Quotes list -> user
- [x] Public training -> user
- [x] Public quote process -> user
- [x] Private training -> user
- [x] Private quote process -> user

Form
- Public quote reservation form
  - [x] Number of seats
- Private quote reservation form
  - [x] Venue dropdown
  - [x] Preferred date
- Public quote form
  - [x] Unit price
  - [x] Discount
  - [x] Wire transfer
  - [x] Accept/ Process button
  - [x] Deny button
- Private quote form
  - Course event fieldset 
    - [x] Start date
    - [x] End date
    - [x] Atp
    - [x] Ai
  - [x] Price
  - [x] Discount
  - [x] Wire transfer
  - [x] Accept/ Process button
  - [x] Deny button

Views
- [x] Quotes ‘public-private’ list per user or for all users with paginator ordered by id desc
- [x] Public training with paginator
- [x] Private training with paginator
- Process form
  - Admin
    - Public
      - pending pricing status
        - [x] Course name read only
        - [x] Start date read only
        - [x] End date read only
        - [x] Atp read only
        - [x] Ai read only
        - [x] Seats number read only
        - [x] Unit price field
        - [x] Discount field
        - [x] Process button
    - pending review status
      - [x] Course name read only
      - [x] Start date read only
      - [x] End date read only
      - [x] Atp read only
      - [x] Ai read only
      - [x] Seats number read only
      - [x] Unit price read only
      - [x] Discount read only
      - [x] Wire transfer read only
      - [x] Accept button
      - [x] Deny button
  - Private
    - pending pricing status ‘basically new course event is created’
      - [x] Course name read only
      - [x] Preferred date read only
      - [x] Venue read only
      - [x] Start date field
      - [x] End date field
      - [x] Atp field
      - [x] Ai field
      - [x] Price field
      - [x] Discount field
      - [x] Process button
    - pending review status
      - [x] Course name read only
      - [x] Preferred date read only
      - [x] Venue read only
      - [x] Start date read only
      - [x] End date read only
      - [x] Atp read only
      - [x] Ai read only
      - [x] Price read only
      - [x] Discount read only
      - [x] Wire transfer read only
      - [x] Accept button
      - [x] Deny button
  - User
    - Public
      - pending payment status
        - [x] Course name read only
        - [x] Preferred date read only
        - [x] Venue read only
        - [x] Start date read only
        - [x] End date read only
        - [x] Atp read only
        - [x] Ai read only
        - [x] Seats number read only
        - [x] Unit price read only
        - [x] Discount read only
        - [x] Wire transfer field
        - [x] Accept button
        - [x] Deny button
    - pending re-payment status
      - [x] pending payment status same display, plus
      - [x] Current wire transfer read only
    - Ready status
      - [x] Course name read only
      - [x] Start date read only
      - [x] End date read only
      - [x] Atp read only
      - [x] Ai read only
      - [x] Seats number read only
      - [x] Unit price read only
      - [x] Discount read only
      - [x] Wire transfer read only
  - Private
    - pending payment status
      - [x] Course name read only
      - [x] Preferred date read only
      - [x] Venue read only
      - [x] Start date read only
      - [x] End date read only
      - [x] Atp read only
      - [x] Ai read only
      - [x] Price read only
      - [x] Discount read only
      - [x] Wire transfer field
      - [x] Accept button
      - [x] Deny button
    - pending re-payment status
      - [x] pending payment status same display, plus
      - [x] Current wire transfer read only
    - Ready status
      - [x] Course name read only
      - [x] Preferred date read only
      - [x] Venue read only
      - [x] Start date read only
      - [x] End date read only
      - [x] Atp read only
      - [x] Ai read only
      - [x] Price read only
      - [x] Discount read only
      - [x] Wire transfer read only

Mails ‘use price form view components’
- [x] Admin public quote pending pricing
  - Subject : New public quote
- [x] Admin public quote pending review
  - Subject : Public quote pending review
- [x] Client public quote pending payment
  - Subject : Public quote pending payment
- [x] Client public quote pending re-payment
  - Subject : Public quote pending re-payment
- [x] Client public quote ready invoice
  - Subject : Public quote invoice
- [x] Admin private quote pending pricing
  - Subject : New private quote
- [x] Admin private quote pending review
  - Subject : Private quote pending review
- [x] Client private quote pending payment
  - Subject : Private quote pending payment
- [x] Client private quote pending re-payment
  - Subject : Private quote pending re-payment
- [x] Client private quote ready invoice
  - Subject : Private quote invoice

**Comment by babanesma** [comment]
- Move private training venue to a new lookup table 
- this warning appears when reserving public or private workflow  

```
( ! ) Warning: htmlspecialchars() expects parameter 1 to be string, object given in /var/www/html/data/mustache/__Mustache_c3fa4b86785ceb97bd915fdd50720415.php on line 301
```
- make quotes listing displays both private and public quotes unless filtered 
- make sure process actions redirect to the quotes listing page

**Comment by babanesma** [comment]
there is a bug on any form 

```
( ! ) Fatal error: Call to a member function setFormViewHelper() on a non-object in /var/www/html/module/Utilities/src/Utilities/Controller/ActionController.php on line 80
```
