### ISSUE TITLE
CGP106 : Live Chat

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#106]
- [x] basic Ratchet Implementation
- View
- [x] create chat template 
- Backend
- [x] create Message Entity
- [x] create broadcast Chat
- [x] online Admins
- [x] implement user-admin Chat
- [x] enhancements
  - [x] updating online users each  5 seconds  
  - [x] sending message user has been disconnected if
    - [x] sending message to disconnected user
    - [x] chat box still open when recipient disconnected  
  - [x] adding x mark to close chat box along with pressing on user in list 
  - [x] open session in all pages

**Comment by babanesma** [comment]
Basic implementation is working , there are some UI bugs 
- [x] message text box should be a text area that expands with more text 
- [x] hitting enter should send the message , shift+enter creates a new line 
- [x] entering large text is breaking the message panel , and make it slides down

**Comment by babanesma** [comment]
Issues : 
- [x] add a close button above the main chat to close the chat and return to "Join Chat" button 
- [x] make all chat divs hover on the main content , not to take other space and increase the page height ( like facebook )

**Comment by babanesma** [comment]
- [x] remove jquery call from code.jquery.com 
- [x] adding chat.css
- [x] sending message to all users with the same recipient id  (Case : opening the same account on more than one browser )
- [x] if the chat server is not up , let the chat client make connection trials to the chat server to check if it is up again or not
