### ISSUE TITLE
CGP107: Course Calendar Save the date

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#107]
- [x] Add A button "Calendar Alert" beside each course event to send a mail with a link to Add event to user's personal calendar
- [x] Add A button "Periodic Notifications" beside each course event to send a mail notifying user with course starting date with the option to stop periodic notifications after subscription

**Comment by lebaz20** [comment]
- Calendar alert
  - [x] calendar alert action
  - [x] use [addToCalendar](http://addtocalendar.com/) library
  - [x] update calendar privileges to set start and end dates and time zone
  - [x] email course event calendar to user
  - [x] ACL for calendar alert 
- Periodic Notifications
  - [x] Periodic Notifications subscribe/ unsubscribe actions
  - [x] ACL for periodic notifications subscribe/ unsubscribe actions
  - [x] Add course event subscription entity
  - [x] Add command to send notifications every x days
  - [x] email course event periodic notification to user
  - [x] Load subscribe/ unsubscribe forms in calendar page

**Comment by babanesma** [comment]
- Calendar alert
  - use bower instead to load the library
