### ISSUE TITLE
CGP108: Proctor Assignment

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#108]
- [x] ATC admin should be able to view nearest ten proctors ordered by location
- [x] ATC admin should be able to assign proctors to exam
- [x] User can have location required in case of proctor only

**Comment by lebaz20** [comment]
- Add proctors to exam book
  - [x] Add proctors to Exam entity
  - [x] Create new exam proctors form
  - [x] Add action/ view to display exam proctors
- Add location to user
  - [x] Use GMap in user new and edit views
  - [x] Add longtitude and latitude to User entity
  - [x] Add Location picker to User form
  - [x] Longtitude and latitude should be required
- Order proctors by location
  - [x] In case of user location edit -> push to sort queue by distance organization id
  - [x] In case of organization location edit -> push to sort queue by distance organization id
  - [x] In case of organization proctor assignment -> push to sort queue by distance organization id
  - [x] In case of organization proctor edit -> push to sort queue by distance organization id
  - [x] Sort all organization users per organization and update their distanceSort
  - [x] Order proctors by distanceSort

**Comment by babanesma** [comment]
- When no proctors are assigned , the add proctors form is not working 
- Display the distance between the proctors and the organization in the form , and their cities
