### ISSUE TITLE
[Testing] CMS

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#117]
- CMS
  - Menus
  - [x] Admin CRUD of Menus
  - [x] Admin CRUD of Menu Items
  - [x]  Activation/Deactivation of Menu items and Menus
  - Static Page
  - [x]  Admin CRUD
  - [x]  Page Details ( Title, Picture/no Picture, Body )
  - [x]  Testing Path vs Page
  - [x]  Activation/Deactivation 
  - Press Release
  - [x]  Admin CRUD 
  - [x]  Page Listing ( Title, Picture, Author, Summary, Details Link )
  - Page Details ( Title, Picture, Author, Date, Summary, Body )
    - [x]  Subscription
    - [x]  PDF
    - [x]  Send to friend

**Comment by ahmedReda1** [comment]
We're having a problem with testing the attachment of file in press release crud returnig 

#### [curl] 18: transfer closed with outstanding read data remaining [url] http://local-certigate.com/cms/page/new

But it still creates the release entity

**Comment by ahmedReda1** [comment]
We're having problem with created static pages that needed to be attached to a menu item to be accessed ... so I've created this issue #121 
that we need to make the page available after creation even if not attached to a menu item
