### ISSUE TITLE
CGP121: [BUG] Page Not Found

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#121]
Newly created Pages return  -> "page not found"  if  the page didn't added as menu item
but the seed created pages are working [fine] 

![screenshot from 2016-04-24 15 02 08](https://cloud.githubusercontent.com/assets/11410166/14767754/cd4260ac-0a2d-11e6-8d7e-f2e502a41c54.png)

**Comment by babanesma** [comment]
This case is not needed now
