### ISSUE TITLE
CGP125: [BUG] edit link in resources list fails

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#125]
Page not found error is thrown when clicking edit in `/resources` listing page

Tech Note : make all urls for resources start by `/courses/resources`

**Comment by babanesma** [comment]
The error is still appearing when editing the resource 
And the tech note is not applied 

```
Tech Note : make all urls for resources start by /courses/resources
```

**Comment by ahmedReda1** [comment]
Bug Whenever needing to edit 1 specific resource:
- Notice: Undefined index: translatorHandler in /var/www/html/module/Courses/src/Courses/Form/ResourceForm.php on line 63
- Notice: Undefined index: resourceModel in /var/www/html/module/Courses/src/Courses/Form/ResourceForm.php on line 64
- Fatal error: Call to a member function getTranslatedResourceTypes() on a non-object in /var/www/html/module/Courses/src/Courses/Form/ResourceForm.php on line 117

**Comment by ahmedReda1** [comment]
- [x] fix edit URL  /resources 
- [x] fix previous bugs
  - [x] add translatorHandler to form options
  - [x] add resourceModel to from options
- [x] change all resource URLs from / resources... to /courses/resources
