### ISSUE TITLE
CGP126: [BUG] Resources' types are saved in DB as text

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#126]
We need a Lookup table for resource types, so that in each resource entry, type is just an id for that type

**Comment by ahmedReda1** [comment]
- [x] Create new Entity ResourceType
- [x] Connect it with Entity Resource
- [x] Create Seeds for resource types ( 6 types )
- [x] Fix Edit & Create actions 
  - [x] fix /resources
  - [x] fix edit  /resource/edit/<course_id>
  - [x] fix Bulk upload
