### ISSUE TITLE
CGP127: [BUG] Display only arabic or english content in listing

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#127]
Based on current locale, arabic name or english name should be displayed, not both

This covers all listing and details pages in the system and mails sent from the system

**Comment by ahmedReda1** [comment]
Modules needed this enhancement :
- [x] CMS
  - [x] Menus                      /cms/menu
  - [x] Pages                       /cms/page
  - [x] MenuItems                /cms/menuitem
  - [x] Press release            /cms/press-release
  - [x] view page  
- [x] Courses
  - [x] Calendar                    /courses/claendar
  - [x] Courses                     /courses
  - [x] instructor-calendar     /courses/instructor-calendar
  - [x] instructor-tarining       /courses/instructor-training
  - [x] my-courses                /courses/mycourses
  - [x] course-events            /course-events
  - [x] exam requests           /courses/exam/requests
  - [x] outlines index             /courses/outlines/<course_id>
  - [x] quote index                /quote
  - [x] quote private&public  /quote/training/private
  - [x] resources index         /courses/resources/<course_id>
- [x] Organizations 
  - [x] organization-user index   /organization-users/<org_id>
  - [x] ATCS                               /organizations/atcs
  - [x] ATPS                               /organizations/atps
  - [x] Distributors                      /organizations/distributors
  - [x] Re-sellers                        /organizations/resellers
  - [x] my-organizations            /organizations/myorganizations
  - [x] organizations-index        /organizations
- [x] Users
  - [x] Users-index                    /users
  - [x] instructors                       /users/instructors 
  - [x] roles index                      /users/roles

NOTE : More (details pages skipped ... cause it supposed to have both Arabic and English data)
