### ISSUE TITLE
CGP13: Course Resources

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#13]
Introduction:
1- Each course has its own resources
2- Resources are 3 types:
- Presentations 
- Activities
- Exams

3- Admin or ATP can attach those resources to course using normal CRUD operations
4- Instructor can download those resources

Fields
1- Title
2- Upload File

**Comment by babanesma** [comment]
- /resources produces exception error 
- add a message next to the label to indicate the files types allowed , and enable it in the upload form
