### ISSUE TITLE
CGP136: [BUG] Modals inconsistent all over the system

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#136]
Unify modals all over the system to hold same structure and design, Revise specially modals in issue tracker pages and send to friend press release,
We are using [bootbox](http://bootboxjs.com/) which is a js library that generates bootstrap modal HTML needed effortlessly

**Comment by ahmedReda1** [comment]
all modals changed except organizations agreements cause they are related to operations in #160
