### ISSUE TITLE
CGP143: [BUG] send to friend button should be hidden for anonymous users

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#143]
Send to friend button should be hidden for anonymous users

TBD : should /press/id be anonymous or should it be restricted only for users

**Comment by babanesma** [comment]
@ahmedelbougha Should press release pages be available for guests or not ? 
And if they are , should send to friend button available also for guests or not ?

**Comment by babanesma** [comment]
based on the last demo we agreed that send to a friend should be public

**Comment by ahmedReda1** [comment]
STF & download is already public buttons
