### ISSUE TITLE
CGP144: [BUG] Press Release

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#144]
1. Subscription messages can be minpulated by the link like following picture  

![real](https://cloud.githubusercontent.com/assets/11410166/14889205/14798d32-0d5e-11e6-94df-7691f5a71ecf.png)

tech note : use flash message

**Comment by babanesma** [comment]
These errors are appearing when viewing `cms/press-release` for the first time 

```
Notice: Undefined offset: 0 in /var/www/html/module/CMS/src/CMS/Controller/PressReleaseController.php on line 64

Notice: Undefined offset: 0 in /var/www/html/module/CMS/src/CMS/Controller/PressReleaseController.php on line 65

Notice: Undefined offset: 1 in /var/www/html/module/CMS/src/CMS/Controller/PressReleaseController.php on line 66
```

Btw , the first notice is disappearing when logged in
