### ISSUE TITLE
CGP147: [BUG] Proctor, Student and Instructor can register new users

### ISSUE THREAD

**Issue by lebaz20** [camelcasetechsd/certigate#147]
Only Admin, training manager and test center admin should be able to create new users,
Others should get access forbidden

**Comment by babanesma** [comment]
separate the registration action from creating new users action 
make registration action available only for guests , and create new users available only for Admin , Training manager and Test Center Admin

**Comment by ahmedReda1** [comment]
- [x] create registration action
- [x] add new seeds for user module roles
- [x] make register anonymous 
- [x] make /users/new for TM &  TCA  & ADMIN
- [x] prevent users but Admin && TCA &&TM  to hit  /register if they already logged in
