### ISSUE TITLE
CGP15: Ask the Expert

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#15]
Introduction:
Ask the expert is a platform to ask questions which can be answered by people, where the user can rate the answers and questions.

Task:
Setup: Question and Answer opensource application from (http://www.question2answer.org/)

Tech Note:
- check this [installation guide](http://www.question2answer.org/single-sign-on.php) to link the new application with our users table

**Comment by babanesma** [comment]
- restrict adding questions to logged in users
