### ISSUE TITLE
CGP16: Book Exam Session

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#16]
Introduction: Test Center Admin can perform an action of booking exam session at specific date.

Features:
1- Testing Center Admin go to Book Exam Session
2- There's a calendar (text field) the admin can use it to select the date of the exam
3- The first available day must be after 10 days from this day
4- Once submitted 
    a- email shall be sent to TVTC with (Accept) and (Decline) links
    b- email shall be sent to CertiGate Operations to know about this request
    c- the request shall be saved in the database
    d- the request shall be displayed in the admin listed as pending (status field in database), and pending TVTC approval (tvtc_status field to pending)
5- TVTC Actions
     a- Accept: This changes the field of tvtc_status to accepted 
     b- Decline: This changes the field of tvtc_status to declined 
     c- Nothing: After 3 days this changes tvtc_status to  3 days pending ( this is different from pending), which notifies the Operations they need to call TVTC
6- CertiGate Admin can approve, disapprove the request regardless TVTC approval

Fields:
1- ATC
2- Course
3- Number of Students 
4- Date

**Comment by lebaz20** [comment]
@babanesma  Issue in console route is now fixed

**Comment by ahmedReda1** [comment]
last commit was meant for #22

**Comment by babanesma** [comment]
@ahmedReda1 
- change Courses\Module to imlement ConsoleUsageProviderInterface & ConsoleBannerProviderInterface to add more information about the command

**Comment by babanesma** [comment]
@lebaz20  add email notification function after finishing #21

**Comment by babanesma** [comment]
- change the email content to be generated from a view template 
- put all the email template in the notifications module
