### ISSUE TITLE
CGP162: [BUG] Create new seeds 

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#162]
Create new seeds  as needed for complete the testing for the following entities :
- [x] New Re-Seller Role
- [x] New Distributor Role
- [x] New TM user  with username&&password "tmuser2"
- [x] New TCA user  with username&&password "tcauser2"
- [x] New Distributor user  with username&&password "distributor"
- [x] New Distributor user  with username&&password "distributor2"
- [x] New Reseller user  with username&&password "reseller"
- [x] New Reseller user  with username&&password "reseller2"
- [x] New Distributor organization
- [x] New Re-Seller organization
- [x] Add new statements fro the new roles
- [x] fix : tmuser is assigned as TCA  in organization "dummyboth"

**Comment by babanesma** [comment]
merge phase2 with this branch , as there were some changes in seeds merged already in phase2
