### ISSUE TITLE
CGP185: [BUG] Clanedar Events

### ISSUE THREAD

**Issue by ahmedReda1** [camelcasetechsd/certigate#185]
- [x] deactivated course events still appearing in /courses/calendar 
- [x] enroll action for course Event .. need to prevent it before reaching Estore part 
  ![trials](https://cloud.githubusercontent.com/assets/11410166/15708364/8441fcfc-27fe-11e6-9cd2-42c5566f4c69.png)
- [x]  Course without course events still appearing in /calendar

**Comment by babanesma** [comment]
move the logic of filtering deactivated course events from the view templates to the models instead
