### ISSUE TITLE
CGP2: Menu System

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#2]
Create menu system module to allow the admin to handle the different paths and menu items of the system.
This is giving the system the flexibility to create dynamic menus that are being displayed in the frontend.
According to our discussion today, we need to add Menu module to:
1- Handle different menu items in the system, by creating menu item and assign them to paths
2- To use with static pages to be able to give the page its own path and URL.

**Comment by lebaz20** [comment]
@ahmedelbougha @babanesma  Although, Generated menu has CSS style issues, and still appear for all users including Admin role user, it is ready now for testing

**Comment by lebaz20** [comment]
Now menu will not appear for any logged in user with Admin role, Instead will appear for other roles and for anonymous users
