### ISSUE TITLE
[Production issues] Issues in user form 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#208]
- [x] Phone format to the following format 
  Field for Country code dropdown menu with countries  + Field for area code (3 digits) + Field for phone Number (6 to8 digits)
- [x] Convert the following mandatory fields to optional fields.
  - First Name in Arabic
  - Last Name in Arabic
  - Identification Type
  - Identification Number
  - Hijri Identification Expiry Date
  - Identification Expiry Date
  - Hijri Date Of Birth
  - Date Of Birth
  - Address Line 1
  - Address Line 1 in Arabic
- [x]      we need to make Saudi Arabia is the selected country.
- [x]   We need to remove field Language.

**Comment by ahmedReda1** [comment]
@babanesma making address 1 not required or empty returns 'trials limit reached' error of Estore , it seems that it needs an address to create Estore account , so i'll leave it as its for now

**Comment by ghost** [comment]
You can leave address as a mandatory field, but don't restrict a particular format for it.

**Comment by babanesma** [comment]
@ahmedReda1 
- [x] make Saudi Arabia code the default code 
- [x] make mobile input like the phone input 
- [x] try to narrow the 2 inputs ( phone and mobile ) to be in the same row , not each one in a row .
