### ISSUE TITLE
[Production issues] issues with registeration

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#209]
- [x] Google map is not loading 
- [x] estore welcome email is being sent twice 
- [x] make password and confirm password fields aligned 
- [x] make phone area code validator accepts 2-3 digits

**Comment by ahmedReda1** [comment]
kindly remove point 2 cause it's related to saving without location in point 1 , i tried it myself and got missing longitude error (point 1) , if there's any other errors i did not encounter please attach a screen shot for the error, Thank you

**Comment by babanesma** [comment]
- [x] apply same maps fix to organizations form and to any other form that contains maps
