### ISSUE TITLE
[Production Issues] Multiple errors

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#218]
**Estimated Time for the rest of development : 8 hours**
**Target Date : Mon 14 Nov**

Please check attached document 
[Certigatepro errors_Thu_03_Nov.docx](https://github.com/camelcasetechsd/certigate/files/568518/Certigatepro.errors_Thu_03_Nov.docx)

Document has been updated 
Here are the reported issues 
- [x] No mandatory sign with phone field
- [x] when hitting save after registering a user it returns exception message ( real reason it can not reach estore to create correspondent account there )  
- [x] Organization Registration was not accepted. ( check issue 3 in attached document ) 
No error message
After save, back to the same form without the attached PDFs
When checking from admin site, It’s not in the ATP’s list
- [x] Date has been chosen from the pop up calendar. And it gives error. ( check issue 4 in attached document )

**Comment by HeshamHassan** [comment]
well done
I will test and reply
