### ISSUE TITLE
[Production Issues] issues with the arabic interfae

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#220]
Menus don't transferred in to Arabic when changing the language even with login and log out and even with other browser.

**Comment by lebaz20** [comment]
Menu is displayed with Arabic text with no problems

![screenshot from 2016-11-27 14-07-58](https://cloud.githubusercontent.com/assets/5208251/20648273/eea34c20-b4aa-11e6-9969-cbe00b915452.png)

**Comment by ghost** [comment]
Point 1: is the screenshot this from our server? 
Point 2: the Arabic Menus don't appear immediately when you change the language it takes a while to be changed, I think it is because of cash

**Comment by lebaz20** [comment]
@albehairy @babanesma 
* This screenshot was taken locally, now checked the server, and it has the problem stated above
* I don't have needed credentials for debugging on server

**Comment by lebaz20** [comment]
As an update, no need anymore for debugging on the server
* It's a cache issue, where menu locale is checked one time before caching the menu, and on production cache is rarely flushed, so it will need some time for the change to be active and it will affect all the users, not only the user who asked for
* The solution will be having both english and arabic versions cached, and user locale would be used to pick which version to use

**Comment by babanesma** [comment]
Issue resolved , caching is flushed every time the language is changed
