### ISSUE TITLE
CGP24: Train the trainer course

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#24]
Introduction: this is a special course where the instructor can join train the trainer.

Tasks:
1- Add checkbox ( only for admin ) to make course train the trainer ( it's only one course, so if the admin select another course later it'll be that course and the flag shall be removed from this course )
2- Don't display this course in course calendar
3- This course shall be reached via a link from the menu.

**Comment by lebaz20** [comment]
I added a link for instructor course calendar in primary menu per task requirements

**Comment by babanesma** [comment]
This fatal error appears when attempting to visit /courses/instructor-training

`( ! ) Fatal error: Call to a member function getResources() on a non-object in /var/www/html/module/Courses/src/Courses/Controller/CourseController.php on line 145
`
