### ISSUE TITLE
[Production Issues] Third-Parties Apps Themes

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#243]
- [x] 9. Estore Theme
- [x] 10. Ask the Expert theme

**Comment by HeshamHassan** [comment]
Dear Adham,

About "Ask the expert" issue:
I logged in as a student and when clicking on "ask the expert" then new tab opened with the role "Admin"

About "EStore" issue:
I logged in as a student and when clicking on "EStore", a new tab at the same browser opened with "no role" and need me to log on again. It should be with the same login, isn't it?

Best Regards,
Hesham Hassan | Profissional Certificates Advisor | hhassan@thinkcsi.com<mailto:hhassan@thinkcsi.com>
[cid:image001.png@01D14DF7.7CB62DF0]                                                                                                      [cid:image002.png@01D14DF7.7CB62DF0]
[icon-mobile-phone-hi]+966 5491 93094
[cid:image008.jpg@01D1AB88.ACDC3670]+966 9200 0 4426 Extn. 113
P please keep this email paperless
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s).  It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it.  If you have received this communication in error, please notify me immediately
