### ISSUE TITLE
CGP25: Admin Emails Settings

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#25]
Introduction: there're many notifications in the system that need to be sent to various email addresses

Tasks:
1- Create a setting form for the admin to set the emails of:

```
1- Administrator email ( where the admin can get notification to any email address he wants )
2- Operations email
3- TCTC email
```

**Comment by ahmedReda1** [comment]
@ahmedelbougha  @lebaz20 
i already added them in courses\module.config.php

**Comment by lebaz20** [comment]
@ahmedReda1  They are not related to courses,
Anyway, i will create a seed with same keys ,and then we will have to replace calls to those configurations with DB queries

**Comment by lebaz20** [comment]
@ahmedReda1 
I refactored Exam model to rely on zend factory for deps injection and used cached settings queried from DB to get needed email values instead of saved values in configuration
