### ISSUE TITLE
CGP27: Deactivating page, deactivates its menu item

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#27]
For matter of consistency if I can deactivate page, I suppose I can reactivate it, but currently if I deactivate a page then I have to go to its menu item to reactivate it, which doesn't make sense because what if there's a menu item shared between 2 pages? then this should be completely separate. That's why I consider this as a bug.

**Comment by babanesma** [comment]
this will be resolved along with #59
