### ISSUE TITLE
CGP32: Menu items listing page

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#32]
1- Add filters ( by menu and by status (active/inactive) )
2- Add pager

**Comment by ahmedReda1** [comment]
@babanesma i've created the pagination on the menu item and it works fine but the only issue i encountered was using our query service in the filter method  line 154
it returns an array and the paginator only takes objects so it will work without the calling of toArray() method 

So i created another query service called paginatorQuery and extended query to edit filter method but i've failed to force doctrine to use this implementation as it was time to see my doctor 

so you can neglect the other branch
thanks

**Comment by babanesma** [comment]
- when filtering and the results are only in one page , pagination links disappear but "Pages" title still appear . Remove it .
- when filtering with directurl , it only works when entering the whole url 
  `/organizations` doesn't get any results , while `/organizations/type` gets .
- add page select to the filter form , this will filter menu items that links to pages only
