### ISSUE TITLE
CGP6: Course Administration

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#6]
Introduction:
1. The courses can be created by portal admin or by Team Manager (ATP)
2. The course is accesses by Student, ATP, ATC, CI (certified instructor)
3. Only ATP and Portal Admin No. can see the Student No. field
4. The Student, ATP, ATC and Portal Admin can enroll themselves to the courses
5. The course enrollment is disabled once the Course Capacity = Student No.
6. The admin must approve the course

Course Fields
1. Course Name
2. Course Start Date
3. Course End Date
4. Course Capacity
5. Students No. ( number of students enrolled to that course)
6. ATP Name
7. AI Name
8. Course Brief
9. time
10. duration

**Comment by babanesma** [comment]
- CRUD validators 
  - end date should be after start date
  - capacity should be larger than student number
