### ISSUE TITLE
CGP69: TM and TCA roles

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#69]
The roles of TM (Training Manager):
1. Create/edit ATP
2. Manage ATP accounts (adding/removing TMs)
3. Manage courses
4. Create course evaluation

The roles of TCA (Testing Center Admin):
1. Create/edit ATC
2. Manage ATC accounts (adding/removing TCA, Proctors)
3. Manage book exams

All above actions need user to have needed roles agreement accepted.

**Comment by lebaz20** [comment]
I used wrong id while committing ,so here are the [First 8 commits](https://github.com/camelcasetechsd/certigate/compare/673c7f7ffb55...7a4bfa1d57f8)
