### ISSUE TITLE
CGP7: Create Structure of directory pages

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#7]
Directory pages are pages listing data of ATPs or ATCs.
We don't have the full requirements yet of that listing page, but we can use our time to build their structure.
Structure:
Assume that ATP and/or ATC has the following fields in DB
1- name
2- description
3- email
4- contact_name
5- contact_telephone
6- address
7- date_joined
8- created

The listing page contains many ATP/ATC records with following fields:
1- Name
2- Telephone
3- Trimmed summary
4- more link

If the records are more than 25, show the pager.

Details page shall list the whole ATP/ATC fileds
1- Name
2- Joined (date)
3- Email 
4- Contact Name
5- Contact Telephone
6- Address
7- Description

**Comment by ghost** [comment]
I think you missed the attached email

Best regards,
[Description: cid:image003.png@01CCAF59.D3640780]
Ali Albehairy
Operations Manager

Tel: +966920004426tel:+966920004425
Cell: +966544111882
Email: aalbehairy@ThinkCSI.commailto:aalbehairy@ThinkCSI.com
Skype: albehairy

Our Vision: Set a solid foundation of service excellence that distinguishes our region, earns acclaim, and fosters competitive advantage worldwide.
Our Mission: Turn our clients’ vision into reality by bridging strategy, innovation, creativity, technology, knowledge and deliver unique services that deliver greater value and competitive advantage to our customers.

P please keep this email paperless
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s).  It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it.  If you have received this communication in error, please notify me immediately

**Comment by ahmedelbougha** [comment]
Thanks @albehairy, actually I didn't, I agreed with our developers to create this ticket as way to use time until I get that email from you, so actually they were both ( the email and this ticket ) created about the same time.
Tonight or tomorrow morning I'll discuss the email with rest of the guys En Shaa Allah.
