### ISSUE TITLE
CGP77: CMS Create Form Changes

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#77]
1- Re-organize the fields to match the wireframe attached
2- Add new fields ( picture, type, category, author, summary )
3- 2 types available ( page, press release )
4- 1 category available ( default )
5- Remove old status checkbox, instead use "save and publish" button to set status to active 
6- To deactivate use "unpublish" button

![cms page](https://cloud.githubusercontent.com/assets/8982139/13420502/6646cb72-df8f-11e5-9581-25cc543aafb4.png)

**Comment by lebaz20** [comment]
Update Page entity
- [x] Add summary [nullable text field type] with required validation
- [x] Add author [nullable varchar field type] with required validation
- [x] Add category [nullable varchar field type] with values set from constants class and required validation
  - [x] Create constants class for page categories with one constant 'default'
- [x] Add type [varchar field type] with values set from constants class and required validation
  - [x] Create constants class for page types with two constants 'page' and 'press release'
- [x] Add picture [nullable array field type] with renameAndUpload filter enabled and required validation
- [x] Update exchangeArray function to set new fields if not empty

Update PageForm
- [x] Add type select field with required client-side validation
- [x] Add category select field with required client-side validation
- [x] Add author text field with required client-side validation
- [x] Add picture file field with required client-side validation
- [x] Add summary textArea field with required client-side validation
- Replace status field and create button with three buttons
  - [x] Create constants class for each button 'save', 'save and publish' and 'unpublish'
  - [x] Check button value in data array while saving:
    - [x] value is 'save' and in create stage -> set status to inactive
    - [x] value is 'save' and in edit stage -> do not set status [keep old status]
    - [x] value is 'save and publish' -> set status to active
    - [x] value is 'unpublish' -> set status to inactive

Update page js
- [x] On document ready hide category, author, picture and summary fields
- [x] Check type selector value, if press release -> show the four fields
- [x] Add type selector change event -> to show/hide four fields based on selection

Update page create/edit actions
- [x] Check type and if not press release, set required to false for the four fields; category, author, picture and summary
- [x] File should not be required in edit

Update page seed
- [x] Update Page seed with extra fields holding null except type holding page type
