### ISSUE TITLE
CGP78: Press release Listing page

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#78]
1- Display 10 items per page ( picture, title, summary, more link )
2- There's a pager at the end of page
3- Subscribe button shall subscribe the user to the press release newsletters 
![press release listing](https://cloud.githubusercontent.com/assets/8982139/13428283/39fa8a30-dfc2-11e5-906f-6379dd2af160.png)

**Comment by lebaz20** [comment]
- [x] Add validation for summary to not exceed 1000 characters
  - [x] Add length attribute to form field

Add new action for news listing
- [x] Grant anon. access
- [x] Filter page by type press release
- [x] User is subscribed if his/her id exists in subscription table
- [x] Display subscription form [subscribe button] if not subscribed, or display unsubscribe button
- [x] Use pagination in listing entries to display 10 items per page

Create subscription entity
- [x] Add user_id [oneToOne field type] with unique and required validation
- [x] Add token for each entry set automatically

Create subscription form
- [x] Add subscribe button

Add new action for subscription
- [x] Grant user access
- [x] If user is not logged in -> return proper error message
- [x] Ajax call that would submit subscription for current logged in user
- [x] Return success flag with messages array as json to be displayed

Add new action for unsubscription
- [x] Grant anon. access
- [x] If user is not logged in and no token passed -> return proper error message
- [x] If no user exists for token passed -> return proper error message
- [x] Ajax call that would delete subscription for current logged in user or user with token
- [x] Return success flag with messages array as json to be displayed if no token passed
- [x] Display message in new page if token is passed

Add method to generate unsubscribe url
- [x] Generate unsubscribe url by token if logged in user id is not passed ,else use logged in user id

Login Redirect Back
- [x] Pass current url to login action to redirect to url after successful login
- [x] Passed url is optional

Messages display take type
- [x] Edit messages usage in system [contactUs, organization and course edit actions]
- [x] Add dismissal option to alert 
- [x] Add message type

Add listing view
- [x] Add loop for pages
- [x] Add paginator
- [x] Add subscription form

Add listing js
- [x] Ajax form submission for subscription form

**Comment by babanesma** [comment]
- change the subscribe button to "unsubscribe" after a succesfull subscription 
- add a new job to be triggered after a new press release creation to send an email to the subscribed users
