### ISSUE TITLE
CGP79: Press release details page

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#79]
Contains 
1- Picture
2- Title
3- Author name
4- Date
5- Summary
6- Body
7- Send to friend button
8- Download button

![news details page](https://cloud.githubusercontent.com/assets/8982139/13428754/171168e2-dfc5-11e5-90a2-9e9d5a3c6d7a.png)

**Comment by ahmedReda1** [comment]
- [x] PressController has been created
- [x] details Template has been created
- [x] Access press details page by /press/id
- [x] Making sure that only news appear
- [x] adding modal for contact friend 
- [x] using contact us form for send  to friend  
  - [x] hiding ignored fields  
  - [x] removing requited attribute 
  - [x] adding custom values for ignored fields 
  - [x] new Mail subject and template
  - [x] factory for send to friend (pretty much the same contact to us with some edits)    
- [x] adding domPDF module 
- [x] adding .gitignore file to pagePictures

**Comment by babanesma** [comment]
new bug is created #91
