### ISSUE TITLE
BUG : if page is unpublished its menu item should also be unpublished

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#83]
Steps to reproduce 
1. Open any page from the menu ( http://local-certigate.com/ContactUs ) 
2. In a separate page , go to CMS > Pages 
3. Select this page and unpublish it 
4. the page is still can be viewed while it should redirect to 404 page

**Comment by ahmedReda1** [comment]
- [x] redirect inactive pages to resource not found page 
- [x] remove unpublish button in case of already unpublished pages
