### ISSUE TITLE
CGP87: Course Event Entity

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#87]
1- Course event contains:
    a. course
    b. start date
    c. end date
    d. capacity
    e. students number
    f. Instructor ( Authorized Instructor )
    g. Training Partner ( Authorized Training Partner )
![course event form](https://cloud.githubusercontent.com/assets/8982139/13552760/840abbf4-e378-11e5-9e73-a9fea4987a86.png)

**Comment by lebaz20** [comment]
Create CourseEvent controller
- [x] Add routing for new/edit/delete/index actions
- [x] Add new/edit/delete/index actions
- [x] Add new views for the new actions 

Update CourseEvent create/edit action
- [x] setStudentsNo with 0 in new action
- [x] use validateOrganizationAccessControl check
- [x] use validateForm check

Update CourseEvent index action
- [x] use validateOrganizationAccessControl check
- [x] implement filtration in case of training manager to view course events for organizations that belong to the current user

Grant access to TM
- [x] use validateOrganizationAccessControl check in new actions [create/edit/index]
- [x] update ACL seed and fixture with new access list

Update CourseEvent form
- [x] Add userId property to filter organizations by
- [x] Add course select

Update course index view
- [x] Add link to course events per course
- [x] Update admin menu with course events link
