### ISSUE TITLE
CGP89: My Courses

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#89]
Create a page where the user can see his/her own courses
![my courses](https://cloud.githubusercontent.com/assets/8982139/13565571/7f937016-e459-11e5-9a5a-87af1eb2f36c.png)

**Comment by ghost** [comment]
Regards,
Ali Albehairy

On Mar 7, 2016, at 12:41 PM, ahmedelbougha <notifications@github.com<mailto:notifications@github.com>> wrote:

Create a page where the user can see his/her own courses
[my courses]https://cloud.githubusercontent.com/assets/8982139/13565571/7f937016-e459-11e5-9a5a-87af1eb2f36c.png

##

**Comment by ahmedReda1** [comment]
- [x] add seed for user enrolled in  a course (username : instructor  pass : useruser)
- [x] create controller with route /courses/mycourses 
- [x] make the route available for students and instructors along with admin roles 
- [x] add paginator

**Comment by babanesma** [comment]
this issue branch is CGP89_My_Courses is merged already into #88 branch ( 20150306_mlabib_course_changes ) 
when #88 is resolved , its branch along with this branch will be merged into development branch
