### ISSUE TITLE
CGP9: Organization Setup

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#9]
Introduction
1. After registration, the user has the ability to create new organization
2. If the user agreed on Training manager s/he can create ATP
3. If the user agreed on Testing Center Administrator s/he can create ATC
4. Fields marked (ATP only), are being displayed while creating ATP
5. Fields marked (ATC only), are being displayed while creating ATC
6. All fields are displayed if the user creating an organization that is ATP and ATC
7.  Fields marked with \* are mandatory
8. DDM = Dropdown 

Organization form fields.
-   Commercial Name *
-   Location(MAP)
-   Owner Name *
-   Owner National ID *
-   CR No. *
-   CR Expire Date *
-   CR Attachment *
-   ATP License No.  * (ATP Only)
-   ATP License Expire Date * (ATP Only)
-   ATP License Attachment * (ATP Only)
-   ATC License No. * (ATC Only)
-   ATC License Expire Date * (ATC Only)
-   ATC License Attachment * (ATC Only)
-   address/line1 *
-   address/line2 *
-   address/city *
-   ZIP Code *
-   Phone1 *
-   Phone2
-   Phone3
-   Fax
-   Website *
-   Official Email *
-   Training Manager (Username) + link to the individual reg. if he doesn’t have a username (ATP Only)
-   Test Center Admin (Username) + link to the individual reg. if he doesn’t have a username (ATC Only)
-   Focal Contact Person (Username)+ link to the individual reg. if he doesn’t have a username *
-   Number of Labs * (ATC Only)
-   Number of PCs # / Lab * (ATC Only)
-   Number of Classes # * (ATP Only)
-   Number of PCs # / Class * (ATP Only)
-   Internet Speed / Lab *  (ATC Only)
-   Operating System / Lab DDM *  (ATC Only)
-   Operating System Language DDM *  (ATC Only)
-   Microsoft Office Ver. / Lab DDM *  (ATC Only)
-   Microsoft Office Language DDM *   (ATC Only)
-   ATC Agreement (link to modal with with agree/decline buttons) *   (ATC Only)
-   ATP Agreement (link to modal with with agree/decline buttons) *   (ATP Only)

**Comment by babanesma** [comment]
- Handle [this exception](https://github.com/camelcasetechsd/certigate/blob/master/module/Organizations/src/Organizations/Model/Organization.php#L222-L224) ( redirect to the form page with an error message )
- remove unneeded property ( $objectManager ) from Organizations\Form\TypeForm 
- retrieve the static lists in the form from one source only ( Organizations\Model\Organization::prepareStatics ) 
- add the attachments directories to the repository with .gitignore file to ignore all the attachements ( [see example](https://github.com/camelcasetechsd/certigate/blob/master/data/mustache/.gitignore) ) 
- move skippedParams to config/module.config.php
