### ISSUE TITLE
CGP90: Course Enrollment workflow

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#90]
The workflow of course enrollment should follow the diagram below

![course booking](https://cloud.githubusercontent.com/assets/8982139/13600662/1173bd2c-e533-11e5-952e-1c333e1b7ce6.png)

**Comment by lebaz20** [comment]
Subtasks
Using our [Open cart wiki](https://github.com/camelcasetechsd/certigate/wiki/Open-Cart)
- [x] Prepare estore installation via deploy script
- [x] Fix session conflict between opencart and zend
- [x] Merge estore DB with normal DB

Edit course entity
- [x] Add product_id [not nullable string field]
- [x] Add price [float field] with required validation
- [x] Add related setters/ getters and update exchangeArray method

Edit course event entity
- [x] Add option_value_id [nullable string field]

Edit course event user entity
- [x] Add status [inactive or active] [int field]
- [x] Add token [unique string field]

Edit course form
- [x] Add price float number field in dollar

Create estore caller using curl/ guzzle
- [x] get api key from estore DB through normal pdo operation
- [x] call route with method, parameters optional using token property if not empty or call login instead
- [x] in case of missing permissions, call login and get token, then update static token property

Create Product on estore
- [x] create new product edge with get, create and update actions
- [x] create new option edge with get, create and update actions
- [x] create new optionValue edge with update action
- Create course 
  - [x] call create product edge setting requires shipping to false before even saving course to set it's product_id
- Edit course 
  - [x] call edit product edge before saving course
- Create course event 
  - [x] call get option with name "course event" ,if not exists call create option with value of current course event
  - [x] call edit option if option exists with value of current course event being added "startDate endDate InstructorName ATPName ATPCity"
  - [x] set option_value_id with new value id in course event
  - [x] call get product by id and get all options 
  - [x] call edit product setting course event option appending current course event to current options
- Edit course event
  - [x] call edit optionValue with new value of current course event

Enroll course
- [x] call cart edge adding product for the course with the option of course event selected
- [x] redirect to "/estore/index.php?route=checkout/cart"
- [x] add user to course event with status inacitve
- [ ] update db used to include paypal enabled
- [x] update db with local and server ip addresses added to api accepted ip addresses "127.0.0.1"
- [x] override ControllerCheckoutSuccess index action to redirect back to calendar if order contained course product with token queried from DB via product id and option value id 
- [x] hide course event if time passed from calendar and more
