### ISSUE TITLE
CGP92: Organization renewal fields

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#92]
1- ATP and ATC organizations have ATP/ATC license data fields ( ATP/ATC license, ATP/ATC license expiration, ATP/ATC license attachment, ATP/ATC license wire transfer )
2- The 4 fields above shall be used for renewal of organization
3- There's cron job shall be set the flag of organization expiration according to expiration date and send notification email 1 week before expiration    

![renewal-form](https://cloud.githubusercontent.com/assets/8982139/13601114/53870432-e536-11e5-8dde-417c615ebb4d.png)

**Comment by ahmedReda1** [comment]
command is :
cd /vagrant
php public/index.php updateExpirationFlag
