### ISSUE TITLE
CGP93: Adding new organization type

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#93]
1- Create new database table organization_type contains all organization type ( 4 types ATP, ATC, Distributor, Re-seller )
2- Make the organization type selection page loading those types automatically 
3- Add 2 new fields in the organization ( Region and Governorate ) ( Multi-select lists linked to database lookup tables )

Notes from team discussion:
1- Fields Region and Governorate entities both are many-to-many with Organizations, which means it needs an intermediate relation

**Comment by ahmedReda1** [comment]
- [x] adding new organizations to /organization/type
- [x] creating new organizationType entity and adding seeds for it
- [x] removing type_both from the system
- [x] change routing technique
- [x] changing js for organization logic
- [x] making type form generate types dynamically
- [x] changing form manipulation technique
- [x] adding new fields for Region and Governorate
- [x] add listing pages for new organiztions  & fix old pages
- [x] remove type attribute from organization entity and fix listing
