### ISSUE TITLE
CGP94: Manage My organizations

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#94]
1- Manage my organizations page contains list of users manageable organizations
2- Every organization has its own list of actions ( Details, Manage, Edit/Renew )
3- In case of organization edit all fields of organization displayed except the 4 fields of renewal
4- In case of organization manage only the 4 fields of renewal are displayed
![my organizations](https://cloud.githubusercontent.com/assets/8982139/13602768/4e7569b0-e541-11e5-9a3d-0b4d1279ec01.png)

**Comment by ahmedReda1** [comment]
- [x] creatig OrganozationMeta entity
- [x] creating my-organization template 
- [x] prevent Distributor & Reseller from managing users
- [x] change renew from renew/orgId  -> renew/orgId/metaId
- [x] making sure that meta -> belongs to organization for security manipulation for renewal
- [x] Who can open this page ?

NOTE: Any one can open this page cause Dist & reseller has no organization users so you can not limit access only for TCA & TM

**Comment by babanesma** [comment]
latest commit here ( d00b2125c20039a94e87d906d6d174dcd448c6a4 ) is intended to be in #95

**Comment by babanesma** [comment]
- /organizations/myorganizations is showing an empty list , and when I try to edit an organization ( /organizations ) this fatal error appears 

> Fatal error: Undefined class constant 'TYPE_BOTH' in /var/www/html/module/Organizations/src/Organizations/Model/Organization.php on line 493

**Comment by ahmedReda1** [comment]
- [x] adding seeds for created organizations  in (organizations & courses)
- [x] fix prepareForDisplay type Both
- [x] fix redirect to noOrganizationUsers Action on press (manage users)  for ATP type 
- [x] add wire transfer to pending data

**Comment by ahmedReda1** [comment]
- [x] adding paginator tomy organizations
